### ISSUE TITLE
No inline styles!

### ISSUE THREAD

**Issue by jsiarto** [DustinOdeh/mi349_blog#1]
https://github.com/DustinOdeh/mi349_blog/blob/69ca4e00e4d631353f6cd4e71b375af8534b80a6/Index.html#L11

**Comment by DustinOdeh** [comment]
Sorry, I should have assigned an ID?

**Comment by jsiarto** [comment]
No, you don't need to worry about _any_ styling in these labs, we haven't covered CSS yet. Styling includes aligning text to the center of the screen. For reference, yes -- you would want to assign a class or ID to this element and make the typography changes in a separate CSS stylesheet. My goal in these labs is to get you to **only** focus on the quality of your markup without regard to the layout in the browser.

**Comment by DustinOdeh** [comment]
I'm sorry, but correct me if I'm wrong, I don't think that it was stated. I was just centering the text to make it look more neat, I didn't expect us to be using the same files again. I don't think I should be marked down in points for doing something extra.

**Comment by jsiarto** [comment]
Points were lost primarily because both files failed validation (https://validator.w3.org/). I understand the need to want to make the rendered HTML look neat--but there are two issues here:
1. It takes away focus from the primary objective of the lab which was to generate valid, semantic HTML
2. Inline CSS is bad-practice--it's not the correct way to achieve what you're trying to do and makes the HTML less semantic, less readable, and less maintainable.

Generally, I try not to make a big deal about students sneaking in CSS into HTML labs, but in this case, the HTML was not done correctly regardless of the added inline CSS.

**Comment by DustinOdeh** [comment]
Thank you
