### ISSUE TITLE
Each blog post should be in its own <article>

### ISSUE THREAD

**Issue by jsiarto** [DustinOdeh/mi349_blog#2]
https://github.com/DustinOdeh/mi349_blog/blob/69ca4e00e4d631353f6cd4e71b375af8534b80a6/Index.html#L32

**Comment by DustinOdeh** [comment]
I did not know that it mattered, sorry for missing that.

**Comment by jsiarto** [comment]
It doesn't change the way anything _looks_. But it matters from a syntactic point of view. We are using HTML to describe the content of our webpage--the `article` helps inform browsers, machines, and humans what kind of content to expect.
